---
- hosts: localhost
  become: yes
  tasks:
  - name: update system
    apt:
      update_cache: yes
  - name: upgrade system
    apt:
      upgrade: yes
  - name: install git
    apt:
      name: git
      state: present
    

- hosts: localhost
  become: yes
  vars:
    folderpath: /home/ansible/nodeapp
    npmpath: /home/ansible/npm
  tasks: 
  - name: install npm
    apt: 
      name: npm
      state: present
      #path: "{{npmpath}}"
  - name: creating nodesetup directory
    file:
      path: "{{folderpath}}"
      state: directory
      mode: 0755

  - name: Download shell script file to download node.js setup file
    command: "curl -sL https://deb.nodesource.com/setup_8.x -o {{folderpath}}/nodesource_setup.sh"
  - name: Execute downloaded script file
    command: "sudo bash {{folderpath}}/nodesource_setup.sh" 
  
  - name: install node js
    apt:
      name: nodejs
      state: present

  - name: copy the code
    template:
      src: "templates/tellform.j2"
      dest: "{{npmpath}}/tellform.js"

  - name: install packages
    command: npm install -g $item
    with_items:
      - yo 
      - grunt
      - grunt-cli
      - bower

  - name: insntall pm2
    npm:
      name: pm2
      global: yes
  - name: "Start nodejs app"
    command: pm2 start {{folderpath}}/tellform.js
      

- hosts: localhost
  become: yes
  tasks:
  - name: install nginx
    apt:
      name: nginx
      state: present
  - name: copy default.j2 file
    template:
      src: templates/default.j2
      dest: /etc/nginx/sites-available/default
    notify: restart nginx
  handlers: 
  - name: restart nginx
    service:
      name: nginx
      state: restarted


    