---
- hosts: all
  become: yes
  tasks:
  - name: update system
    apt:
      update_cache: true

#python specific setting

- hosts: app
  become: yes
  vars:
    folderpath: /home/ansible/pythonapp
  tasks:
  - name: creating pythonapp directory
    file:
      path: "{{folderpath}}"
      state: directory
      mode: 0755
  - name: installing git
    apt:
      name: git
      state: present
  - name: Installing passenger package
    command: "sudo apt-get install -y dirmngr gnupg"
    command: "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7"
    command: "sudo apt-get install -y apt-transport-https ca-certificates"

  
  - name: install python
    apt:
      name: python
      state: present
  
  

